{{- if and .Values.otel.enabled .Values.otel.customConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otel-collector.fullname" . }}-otel-custom-config
  labels:
    {{- include "otel-collector.labels" . | nindent 4 }}
    app: otel-collector
data:
  custom.config.yaml: |
{{ .Values.otel.customConfig | indent 4 }}
{{- end }}