---
{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "clickhouse.adminSecretName" . }}
  namespace: {{ include "clickhouse.namespace" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore }}
    kind: {{ .Values.externalSecrets.secretStoreKind | default "SecretStore" }}

  target:
    name: {{ include "clickhouse.adminSecretName" . }}
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          {{- include "clickhouse.labels" . | nindent 10 }}
      data:
        {{ include "clickhouse.adminSecretKey" . }}: {{ `"{{ .password }}"` }}

  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.adminPasswordPath }}
{{- end }}
